[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.9.6"
dependencies = ["numpy", "opencv-python", "lapx", "scipy", "torch", "onnxruntime"]

[dependency-groups]
dev = [
    "cython-bbox>=0.1.5",
    "lap>=0.5.13",
    "matplotlib>=3.9.4",
]
